<?PHP

/****************************************************************************************************/
/*   FlatMP Functions - Funzioni di FlatMP            	                                            */
/*   ==================================================                                             */
/*                                                                                                  */
/*   Copyright (c) 2009 by ZEB-DEMON                                                                */
/*   http:// www.ZEB-DEMON.info                                                                     */
/*                                                                                                  */
/*   Flatnux adaptation by LWANGAMAN                                                                */
/*   http://johnrdorazio.altervista.org                                                             */
/*                                                                                                  */
/*   This program is free software. You can redistribute it and/or modify it under the terms of     */
/*   the GNU General Public License (ver.2) as published by the Free Software Foundation.           */
/****************************************************************************************************/
switch($_FN['lang']){
	case "it":
    define ("_MP","Messaggi Privati:");
    define ("_LOGINMP","Devi loggarti per visualizzare i tuoi messaggi privati.");
    define ("_CARTELLAMP","SCEGLI CARTELLA MP");
    define ("_RICEVUTIMP","MESSAGGI RICEVUTI");
    define ("_INVIATIMP","MESSAGGI INVIATI");
    define ("_INVIAMP","Invia un messaggio");
    define ("_DAMP","Da");
    define ("_OGGETTOMP","OGGETTO");
    define ("_DATAMP", "DATA");
    define ("_MITTENTEMP","MITTENTE");
    define ("_INDIETROMP","INDIETRO");
    define ("_RISPONDIMP","RISPONDI");
    define ("_INOLTRAMP","INOLTRA");
    define ("_ELIMINAMP","ELIMINA");
    define ("_AGGIORNAMP", "Aggiorna Lista");
    define ("_ELIMINATUTTIMP", "Elimina Tutti");
    define ("_SICURO1MP","Vuoi cancellare il messaggio?");
    define ("_SICUROTUTTIMP","Vuoi cancellare tutti i messaggi?");
    define ("_DESTINATARIOMP","DESTINATARIO");
    define ("_TESTOMP","TESTO");
    define ("_SUBMITMP","Invia il messaggio");
    define ("_NOMECARTELLAMP","NOME CARTELLA:");
    define ("_NOMENUOVACARTELLAMP","NUOVO NOME:");
    define ("_SUBMITNUOVACP","Crea la cartella");
    define ("_SUBMITRINOMINACP","Rinomina la cartella");
    define ("_MANCAOGGETTOMP","Devi inserire un oggetto per il messaggio.");
    define ("_MANCATESTOMP","Non puoi inviare un messaggio vuoto.");
    define ("_HOINVIATOMP","Il messaggio è stato inviato a:");
    define ("_CARTELLACREATAMP","È stata creata la cartella:");
    define ("_CARTELLARINOMINATAMP","La cartella è stata rinominata in:");
    define ("_ASPETTAMP","Attendere...");
    define ("_TORNAMP","Ritorna ai tuoi messaggi");
    define ("_BENVENUTOMP","BENVENUTO!");
    define ("_PRIMOMP","Questo è un messaggio automatico di benvenuto generato da FlatMP.<br />Adesso puoi inviare e ricevere messaggi privati.");
    define ("_NOREADMP", "messaggi non letti");
    define ("_NONCISONOMP", "NON CI SONO MESSAGGI");
    define ("_OPZIONI1MP","Opzioni");
    define ("_OPZIONI2MP","OPZIONI FLATMP");
    define ("_TESTO1MAIL","hai ricevuto un messaggio privato da ");
    define ("_TESTO2MAIL",".\n\nPer leggerlo accedi a ");
    define ("_OGGETTOMAIL","Arrivato un nuovo messaggio privato su ");
    define ("_OPTMAIL","Avvisami tramite e-mail all'arrivo di un nuovo MP.");
    define ("_MPSAVE","SALVA");
    define ("_MPYES","SI");
    define ("_MPNO","NO");
    define ("_GOTOTHENEXTPAGE","Pagina successiva");
    define ("_GOTOTHEPREVIOUSPAGE","Pagina precedente");
    break;
	case "en":
    define ("_MP","Private Messages:");
    define ("_LOGINMP","You must login to view your private messages.");
    define ("_CARTELLAMP","CHOOSE PM FOLDER");
    define ("_RICEVUTIMP","RECEIVED MESSAGES");
    define ("_INVIATIMP","SENT MESSAGGES");
    define ("_INVIAMP","Send a message");
    define ("_DAMP","From");
    define ("_OGGETTOMP","SUBJECT");
    define ("_DATAMP", "DATE");
    define ("_MITTENTEMP","SENDER");
    define ("_INDIETROMP","BACK");
    define ("_RISPONDIMP","RESPOND");
    define ("_INOLTRAMP","FORWARD");
    define ("_ELIMINAMP","ELIMINA");
    define ("_AGGIORNAMP", "Update List");
    define ("_ELIMINATUTTIMP", "Delete All");
    define ("_SICURO1MP","Do you want to delete the message?");
    define ("_SICUROTUTTIMP","Do you want to delete all messages?");
    define ("_DESTINATARIOMP","Recipient");
    define ("_TESTOMP","BODY");
    define ("_SUBMITMP","Send the message");
    define ("_NOMECARTELLAMP","FOLDER NAME:");
    define ("_NOMENUOVACARTELLAMP","NEW NAME:");
    define ("_SUBMITNUOVACP","Make the new folder");
    define ("_SUBMITRINOMINACP","Rename the folder");
    define ("_MANCAOGGETTOMP","The message does not have a subject. The subject is necessary.");
    define ("_MANCATESTOMP","You cannot send an empty messagge.");
    define ("_HOINVIATOMP","The message has been sent to:");
    define ("_CARTELLACREATAMP","The folder has been created:");
    define ("_CARTELLARINOMINATAMP","The folder has been renamed to:");
    define ("_ASPETTAMP","Please wait...");
    define ("_TORNAMP","Return to your messages");
    define ("_BENVENUTOMP","WELCOME!");
    define ("_PRIMOMP","This is an automatic welcome message generated by FlatMP.<br />Now you can send and receive private messages.");
    define ("_NOREADMP", "unread messages");
    define ("_NONCISONOMP", "THERE ARE NO MESSAGES");
    define ("_OPZIONI1MP","Options");
    define ("_OPZIONI2MP","FLATPM OPTIONS");
    define ("_TESTO1MAIL"," you have received a private message from ");
    define ("_TESTO2MAIL",".\n\nIn order to read it go to ");
    define ("_OGGETTOMAIL","A new private message has arrived on ");
    define ("_OPTMAIL","Send me an e-mail when a new PM arrives.");
    define ("_MPSAVE","SAVE");
    define ("_MPYES","YES");
    define ("_MPNO","NO");
    define ("_GOTOTHENEXTPAGE","Next page");
    define ("_GOTOTHEPREVIOUSPAGE","Previous page");
		break;
	case "fr":
    define ("_MP", "Messages privés"); 
    define ("_LOGINMP", "Vous devez être connecté pour consulter vos messages privés."); 
    define ("_CARTELLAMP", "Choisir un dossier MP"); 
    define ("_RICEVUTIMP", "message reçu"); 
    define ("_INVIATIMP", "Message envoyé"); 
    define ("_INVIAMP", "envoyer un message"); 
    define ("_DAMP", "From"); 
    define ("_OGGETTOMP", "objet"); 
    define ("_DATAMP", "DATA"); 
    define ("_MITTENTEMP", "expéditeur"); 
    define ("_INDIETROMP", "BACK"); 
    define ("_RISPONDIMP", "réponse"); 
    define ("_INOLTRAMP", "à terme"); 
    define ("_ELIMINAMP", "DELETE"); 
    define ("_AGGIORNAMP", "Liste mise à jour"); 
    define ("_ELIMINATUTTIMP", "Supprimer tout"); 
    define ("_SICURO1MP", "Voulez-vous supprimer ce message?"); 
    define ("_SICUROTUTTIMP", "Voulez-vous effacer tous les messages?"); 
    define ("_DESTINATARIOMP", "bénéficiaire"); 
    define ("_TESTOMP", "TEXT"); 
    define ("_SUBMITMP", "Envoyer le message"); 
    define ("_NOMECARTELLAMP", "FOLDER NAME"); 
    define ("_NOMENUOVACARTELLAMP", "Nouveau nom:"); 
    define ("_SUBMITNUOVACP", "Créer un répertoire"); 
    define ("_SUBMITRINOMINACP", "Renommer le dossier"); 
    define ("_MANCAOGGETTOMP", "Vous devez entrer un sujet pour le message."); 
    define ("_MANCATESTOMP", "Vous ne pouvez pas envoyer un message vide."); 
    define ("_HOINVIATOMP", "Le message a été envoyé:"); 
    define ("_CARTELLACREATAMP", "Vous avez créé le dossier:"); 
    define ("_CARTELLARINOMINATAMP", "Le dossier a été renommé:"); 
    define ("_ASPETTAMP", "S'il vous plaît attendre ..."); 
    define ("_TORNAMP", "Retour à vos messages"); 
    define ("_BENVENUTOMP", "Bonjour!"); 
    define ("_PRIMOMP", "Ceci est un message automatique généré par bienvenue FlatMP <br /> Vous pouvez maintenant envoyer et recevoir des messages privés.."); 
    define ("_NOREADMP", "non lu"); 
    define ("_NONCISONOMP", "PAS DES MESSAGES"); 
    define ("_OPZIONI1MP","Options");
    define ("_OPZIONI2MP","FLATMP OPTIONS");
    define ("_TESTO1MAIL"," vous avez reçu un messagge privé de ");
    define ("_TESTO2MAIL",".\n\nAfin de le lire allez dans ");
    define ("_OGGETTOMAIL","Un nouveau message privé est arrivé sur ");
    define ("_OPTMAIL","Avertissez-moi par e-mail lorsqu'un nouveau MP arrive.");
    define ("_MPSAVE","SAUVER");
    define ("_MPYES","OUI");
    define ("_MPNO","NO");
    define ("_GOTOTHENEXTPAGE","Page suivante");
    define ("_GOTOTHEPREVIOUSPAGE","Page précédente");
    break;
	case "es":
    define ("_MP", "Mensajes Privados"); 
    define ("_LOGINMP", "Usted debe estar registrado para ver sus mensajes privados."); 
    define ("_CARTELLAMP", "Elegir carpeta MP"); 
    define ("_RICEVUTIMP", "recibió el mensaje"); 
    define ("_INVIATIMP", "Mensaje enviado"); 
    define ("_INVIAMP", "enviar un mensaje"); 
    define ("_DAMP", "De"); 
    define ("_OGGETTOMP", "objeto"); 
    define ("_DATAMP", "DATOS"); 
    define ("_MITTENTEMP", "Remitente"); 
    define ("_INDIETROMP", "BACK"); 
    define ("_RISPONDIMP", "respuesta"); 
    define ("_INOLTRAMP", "Adelante"); 
    define ("_ELIMINAMP", "BORRAR"); 
    define ("_AGGIORNAMP", "Actualizar lista"); 
    define ("_ELIMINATUTTIMP", "Borrar todo"); 
    define ("_SICURO1MP", "¿Quieres eliminar este mensaje?"); 
    define ("_SICUROTUTTIMP", "¿Desea borrar todos los mensajes?"); 
    define ("_DESTINATARIOMP", "Destinatario"); 
    define ("_TESTOMP", "TEXT"); 
    define ("_SUBMITMP", "Enviar el mensaje"); 
    define ("_NOMECARTELLAMP", "CARPETA DE NOMBRE"); 
    define ("_NOMENUOVACARTELLAMP", "nuevo nombre:"); 
    define ("_SUBMITNUOVACP", "Crear directorio"); 
    define ("_SUBMITRINOMINACP", "Cambiar el nombre de la carpeta"); 
    define ("_MANCAOGGETTOMP", "Debe ingresar un asunto para el mensaje."); 
    define ("_MANCATESTOMP", "No se puede enviar un mensaje en blanco."); 
    define ("_HOINVIATOMP", "El mensaje fue enviado:"); 
    define ("_CARTELLACREATAMP", "Se ha creado la carpeta:"); 
    define ("_CARTELLARINOMINATAMP", "La carpeta ha cambiado el nombre:"); 
    define ("_ASPETTAMP", "Por favor, espere ..."); 
    define ("_TORNAMP", "Volver a sus mensajes"); 
    define ("_BENVENUTOMP", "Bienvenido"); 
    define ("_PRIMOMP", "Este es un mensaje automático generado por la bienvenida FlatMP <br /> Ahora puede enviar y recibir mensajes privados.."); 
    define ("_NOREADMP", "sin leer"); 
    define ("_NONCISONOMP", "No hay mensajes"); 
    define ("_OPZIONI1MP","Opciones");
    define ("_OPZIONI2MP","OPCIONES FLATMP");
    define ("_TESTO1MAIL"," ha recibido un mensaje privado de ");
    define ("_TESTO2MAIL",".\n\nPara leer ir a ");
    define ("_OGGETTOMAIL","Un nuevo mensaje privado ha llegado a ");
    define ("_OPTMAIL","Enviar un e-mail cuando llega un nuevo MP.");
    define ("_MPSAVE","SALVA");
    define ("_MPYES","SI'");
    define ("_MPNO","NO");
    define ("_GOTOTHENEXTPAGE","Página siguiente");
    define ("_GOTOTHEPREVIOUSPAGE","Página anterior");
 		break;
	case "de":
    define ("_MP", "Private Nachrichten"); 
    define ("_LOGINMP", "Du musst eingeloggt sein, um private Nachrichten zu sehen."); 
    define ("_CARTELLAMP", "Ordner auswählen PN"); 
    define ("_RICEVUTIMP", "Nachricht empfangen"); 
    define ("_INVIATIMP", "Nachricht gesendet"); 
    define ("_INVIAMP", "Senden einer Nachricht"); 
    define ("_DAMP", "Von"); 
    define ("_OGGETTOMP", "Objekt"); 
    define ("_DATAMP", "DATA"); 
    define ("_MITTENTEMP", "Absender"); 
    define ("_INDIETROMP", "Zurück"); 
    define ("_RISPONDIMP", "Antwort"); 
    define ("_INOLTRAMP", "Vorwärts"); 
    define ("_ELIMINAMP", "Löschen"); 
    define ("_AGGIORNAMP", "Liste aktualisieren"); 
    define ("_ELIMINATUTTIMP", "Delete All"); 
    define ("_SICURO1MP", "Wollen Sie diese Nachricht wirklich löschen?"); 
    define ("_SICUROTUTTIMP", "Wollen Sie alle Nachrichten löschen?"); 
    define ("_DESTINATARIOMP", "Empfänger"); 
    define ("_TESTOMP", "Text"); 
    define ("_SUBMITMP", "Senden Sie die Nachricht"); 
    define ("_NOMECARTELLAMP", "FOLDER NAME"); 
    define ("_NOMENUOVACARTELLAMP", "Neuer Name:"); 
    define ("_SUBMITNUOVACP", "Verzeichnis erstellen"); 
    define ("_SUBMITRINOMINACP", "Benennen Sie den Ordner"); 
    define ("_MANCAOGGETTOMP", "Sie müssen einen Betreff für die Nachricht."); 
    define ("_MANCATESTOMP", "Sie können nicht senden Sie eine leere Nachricht."); 
    define ("_HOINVIATOMP", "Die Nachricht wurde gesendet:"); 
    define ("_CARTELLACREATAMP", "Sie haben die Ordner erstellt:"); 
    define ("_CARTELLARINOMINATAMP", "Der Ordner wurde umbenannt:"); 
    define ("_ASPETTAMP", "Bitte warten ..."); 
    define ("_TORNAMP", "Zurück zu Ihrer Beiträge"); 
    define ("_BENVENUTOMP", "Willkommen!"); 
    define ("_PRIMOMP", "Dies ist eine automatisierte Mitteilung von FlatMP willkommen erzeugt <br /> Sie jetzt senden und empfangen können private Nachrichten.."); 
    define ("_NOREADMP", "ungelesen"); 
    define ("_NONCISONOMP", "Keine Nachrichten"); 
    define ("_OPZIONI1MP", "Optionen");
    define ("_OPZIONI2MP", "FLATMP Optionen ");
    define ("_TESTO1MAIL", "Sie haben eine private Nachricht von empfangen");
    define ("_TESTO2MAIL", "\n\nIn um lesen zu gehen.");
    define ("_OGGETTOMAIL", "Eine neue private Nachricht ist angekommen auf");
    define ("_OPTMAIL", "Senden Sie mir eine E-Mail, wenn eine neue Uhr ankommt.");
    define ("_MPSAVE", "SPEICHERN");
    define ("_MPYES", "JA");
    define ("_MPNO", "NEIN");
    define ("_GOTOTHENEXTPAGE","Nächste Seite");
    define ("_GOTOTHEPREVIOUSPAGE","Vorherige Seite");
		break;
	case "ru":
    DEFINE ("_MP", "Личные сообщения"); 
    DEFINE ("_LOGINMP", "Вы должны войти в систему для просмотра личных сообщений."); 
    DEFINE ("_CARTELLAMP", "Депутат Выбрать папку"); 
    DEFINE ("_RICEVUTIMP", "сообщение получено"); 
    DEFINE ("_INVIATIMP", "Сообщение отправлено"); 
    DEFINE ("_INVIAMP", "Отправить сообщение"); 
    DEFINE ("_DAMP", "С"); 
    DEFINE ("_OGGETTOMP", "объект"); 
    DEFINE ("_DATAMP", "данные"); 
    DEFINE ("_MITTENTEMP", "отправитель"); 
    DEFINE ("_INDIETROMP", "Назад"); 
    DEFINE ("_RISPONDIMP", "Ответить"); 
    DEFINE ("_INOLTRAMP", "Вперед"); 
    DEFINE ("_ELIMINAMP", "Удалить"); 
    DEFINE ("_AGGIORNAMP", "Обновить список"); 
    DEFINE ("_ELIMINATUTTIMP", "Удалить все"); 
    DEFINE ("_SICURO1MP", "Вы хотите удалить это сообщение?"); 
    DEFINE ("_SICUROTUTTIMP", "Вы хотите удалить все сообщения?"); 
    DEFINE ("_DESTINATARIOMP", "Получатель"); 
    DEFINE ("_TESTOMP", "текст"); 
    DEFINE ("_SUBMITMP", "Отправить сообщение"); 
    DEFINE ("_NOMECARTELLAMP", "FOLDER NAME"); 
    DEFINE ("_NOMENUOVACARTELLAMP", "Новое имя:"); 
    DEFINE ("_SUBMITNUOVACP", "Создать каталог"); 
    DEFINE ("_SUBMITRINOMINACP", "Переименование папки");
    DEFINE ("_MANCAOGGETTOMP", "Вы должны ввести тему сообщения."); 
    DEFINE ("_MANCATESTOMP", "Вы не можете отправить пустое сообщение."); 
    DEFINE ("_HOINVIATOMP", "сообщение было отправлено:"); 
    DEFINE ("_CARTELLACREATAMP", "Вы создали папки:"); 
    DEFINE ("_CARTELLARINOMINATAMP", "папка были переименованы:"); 
    DEFINE ("_ASPETTAMP", "Пожалуйста, подождите ..."); 
    DEFINE ("_TORNAMP", "Возвращение на Ваши сообщения");
    DEFINE ("_BENVENUTOMP", "Добро пожаловать!"); 
    DEFINE ("_PRIMOMP", "Это автоматическое сообщение порожденных FlatMP приветствуем <br /> Теперь Вы можете отправлять и получать личные сообщения.."); 
    DEFINE ("_NOREADMP", "непрочитанные"); 
    DEFINE ("_NONCISONOMP", "нет сообщений"); 
    define ("_OPZIONI1MP", "Параметры");
    DEFINE ("_OPZIONI2MP", "FLATPM Options");
    DEFINE ("_TESTO1MAIL", "Вы получили сообщение от");
    DEFINE ("_TESTO2MAIL", "\n\nВ того, чтобы читать это пойти.");
    DEFINE ("_OGGETTOMAIL", "новое личное сообщение прибыл на");
    DEFINE ("_OPTMAIL", "Пришлите мне по электронной почте, когда новые PM приходит.");
    DEFINE ("_MPSAVE", "Сохранить ");
    DEFINE ("_MPYES", "ДА");
    DEFINE ("_MPNO", "нет");
    define ("_GOTOTHENEXTPAGE","Следующая страница");
    define ("_GOTOTHEPREVIOUSPAGE","Предыдущая страница");
}
?>